using System;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Diagnostics;
using System.Windows.Forms;
using SystemMaintenance.Core;

namespace SystemMaintenance.Controls
{
    public class ReportViewerControl : UserControl
    {
        private ListView lstReports;
        private Label lblHeader;

        public ReportViewerControl()
        {
            this.Dock = DockStyle.Fill;
            this.BackColor = ThemeManager.GetContentColor(ConfigManager.IsDarkMode);

            lblHeader = new Label {
                Text = "Maintenance Reports",
                Font = new Font("Segoe UI", 16F, FontStyle.Regular),
                Dock = DockStyle.Top,
                Height = 50,
                TextAlign = ContentAlignment.MiddleLeft,
                Padding = new Padding(10, 0, 0, 0),
                ForeColor = ThemeManager.GetTextColor(ConfigManager.IsDarkMode)
            };

            lstReports = new ListView {
                Dock = DockStyle.Fill,
                View = View.Details,
                FullRowSelect = true,
                BackColor = ThemeManager.GetCardColor(ConfigManager.IsDarkMode),
                ForeColor = ThemeManager.GetTextColor(ConfigManager.IsDarkMode),
                BorderStyle = BorderStyle.None
            };

            lstReports.Columns.Add("Date", 150);
            lstReports.Columns.Add("Report Name", 400);
            lstReports.Columns.Add("Size", 100);

            lstReports.DoubleClick += (s, e) => {
                if (lstReports.SelectedItems.Count > 0) {
                    string path = (string)lstReports.SelectedItems[0].Tag;
                    try { Process.Start(path); } catch { MessageBox.Show("Could not open report."); }
                }
            };

            this.Controls.Add(lstReports);
            this.Controls.Add(lblHeader);

            RefreshReports();
        }

        public void RefreshReports()
        {
            lstReports.Items.Clear();
            string desktop = Environment.GetFolderPath(Environment.SpecialFolder.Desktop);

            // Pattern match likely report names (generated by our scripts)
            // Format: Name_yyyyMMdd_HHmm.html
            var files = Directory.GetFiles(desktop, "*_*.html")
                                 .Select(f => new FileInfo(f))
                                 .OrderByDescending(f => f.LastWriteTime);

            foreach (var f in files)
            {
                // Simple heuristic to filter only our reports
                if (f.Name.Contains("_202") && f.Name.EndsWith(".html"))
                {
                    var item = new ListViewItem(f.LastWriteTime.ToString("g"));
                    item.SubItems.Add(f.Name);
                    item.SubItems.Add(FormatSize(f.Length));
                    item.Tag = f.FullName;
                    lstReports.Items.Add(item);
                }
            }
        }

        public void ApplyTheme()
        {
            this.BackColor = ThemeManager.GetContentColor(ConfigManager.IsDarkMode);
            lblHeader.ForeColor = ThemeManager.GetTextColor(ConfigManager.IsDarkMode);
            lstReports.BackColor = ThemeManager.GetCardColor(ConfigManager.IsDarkMode);
            lstReports.ForeColor = ThemeManager.GetTextColor(ConfigManager.IsDarkMode);
        }

        private string FormatSize(long bytes)
        {
            if (bytes > 1024 * 1024) return (bytes / 1024 / 1024) + " MB";
            if (bytes > 1024) return (bytes / 1024) + " KB";
            return bytes + " B";
        }
    }
}
